name: Make gen and check diff

on:
  pull_request:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  check-diff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod download

    - name: Run make gen
      run: make gen

    - name: Check for changes
      run: |
        git diff --exit-code
